In [1]:
password = "Mortymer2025"
port = "5432"
db = "pccomponentes_ml"

DATABASE_URI: str = f"postgresql://postgres:{password}@localhost:{port}/{db}"

print("DATABASE_URI creada correctamente")

DATABASE_URI creada correctamente

In [2]:
from pathlib import Path
import sys

current_dir = Path.cwd()

if current_dir.name == "notebooks":
    project_root = current_dir.parent
else:
    project_root = current_dir

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

print(f"Raiz del proyecto: {project_root}")

Raiz del proyecto: c:\Visual Code\PC_COMPONENTES\pccomponentes-ml-analysis

In [3]:
from database.conexion import conectar_postgresql
import database.consultas as consultas

print("Modulos importados correctamente")

Modulos importados correctamente

In [4]:
conn = conectar_postgresql(DATABASE_URI)

print("Conexion creada correctamente")

Conexion creada correctamente

In [5]:
productos = consultas.obtener_productos(conn)

productos

[(1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  Decimal('579.90')),
 (2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  Decimal('339.90'))]

In [6]:
resumen_productos = consultas.obtener_resumen_productos(conn)

resumen_productos

[(1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  Decimal('579.90'),
  Decimal('4.70'),
  461,
  Decimal('93.00'),
  'NVIDIA GeForce RTX 5070',
  '12 GB',
  'GDDR7',
  '192 bits',
  409,
  38,
  4,
  2,
  8),
 (2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  Decimal('339.90'),
  Decimal('4.40'),
  46,
  Decimal('97.00'),
  'NVIDIA GeForce RTX 5060',
  '8 GB',
  'GDDR7',
  '128 bits',
  35,
  5,
  1,
  1,
  4)]

In [7]:
import pandas as pd

columnas_resumen = [
    "producto_id",
    "modelo",
    "marca",
    "precio",
    "valoracion_media",
    "numero_total_opiniones",
    "porcentaje_recomendacion",
    "gpu",
    "memoria_vram",
    "tipo_memoria",
    "bus_memoria",
    "estrellas_5",
    "estrellas_4",
    "estrellas_3",
    "estrellas_2",
    "estrellas_1"
]

df_resumen_productos = pd.DataFrame(resumen_productos, columns=columnas_resumen)

df_resumen_productos

,producto_id,modelo,marca,precio,valoracion_media,numero_total_opiniones,porcentaje_recomendacion,gpu,memoria_vram,tipo_memoria,bus_memoria,estrellas_5,estrellas_4,estrellas_3,estrellas_2,estrellas_1
0,1,MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 R...,MSI,579.90,4.70,461,93.00,NVIDIA GeForce RTX 5070,12 GB,GDDR7,192 bits,409,38,4,2,8
1,2,Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7...,Palit,339.90,4.40,46,97.00,NVIDIA GeForce RTX 5060,8 GB,GDDR7,128 bits,35,5,1,1,4

In [8]:
df_resumen_productos["precio"] = df_resumen_productos["precio"].astype(float)
df_resumen_productos["valoracion_media"] = df_resumen_productos["valoracion_media"].astype(float)
df_resumen_productos["porcentaje_recomendacion"] = df_resumen_productos["porcentaje_recomendacion"].astype(float)

df_resumen_productos

,producto_id,modelo,marca,precio,valoracion_media,numero_total_opiniones,porcentaje_recomendacion,gpu,memoria_vram,tipo_memoria,bus_memoria,estrellas_5,estrellas_4,estrellas_3,estrellas_2,estrellas_1
0,1,MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 R...,MSI,579.9,4.7,461,93.0,NVIDIA GeForce RTX 5070,12 GB,GDDR7,192 bits,409,38,4,2,8
1,2,Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7...,Palit,339.9,4.4,46,97.0,NVIDIA GeForce RTX 5060,8 GB,GDDR7,128 bits,35,5,1,1,4

In [9]:
resenas_con_producto = consultas.obtener_resenas_con_producto(conn)

resenas_con_producto

[(1,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'seikozertwo',
  Decimal('5.0'),
  'La NVIDIA GeForce RTX 5070 es una de las mejores opciones para jugadores exigentes y creadores de contenido.',
  'Excelente rendimiento en 1440p. Arquitectura nueva generacion. Buen rendimiento en tareas creativas.',
  'Ninguno hasta la fecha.'),
 (2,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'TLG1983',
  Decimal('0.5'),
  'Antes de comprar esta grafica que sepais que su precio relativamente barato es por algo. Es una loteria, este modelo tiene problemas conocidos con el conector de alimentacion. Si tienes suerte es una ganga, sino te toca gestionar la devolucion, como fue mi caso.',
  'No detectados.',
  'Problemas conocidos con el conector de alimentacion. Posible devolucion del producto.'),
 (4,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'sime_kwode',
  Decimal('3.5'),
  'Es una GPU de gama media muchos la consideran media-baja, pero puedes correr cualquier juego en Ultra. No soporta muy bien el ray tracing en juegos como Fortnite, Elden Ring, Cyberpunk 2077, pero por el precio que tiene hace un trabajo mas que decente.',
  'Funciona decentemente. Relacion calidad/precio. Tiene 2 ventiladores integrados. Los 12GB deberian ser suficientes para casi todo. No se sobrecalienta. Tiene DLSS4.',
  'No presenta mucha mejoria frente a RTX mas antiguas. Conviene mirar benchmarks con juegos que quieras jugar. Puede flaquear en el campo de ray tracing.'),
 (5,
  2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  'YosuMax',
  Decimal('4.0'),
  'Muy buen rendimiento para el precio que tiene. No conocia esta marca, tenia mis dudas antes de comprarla, pero la primera impresion es buena. Acabo de instalarla, aun la he probado poco. Veremos si aguanta el paso del tiempo, de momento creo que hay que darle un voto de confianza a esta marca.',
  'Precio, aunque no es barata, es la mas economica de su rango. Buen rendimiento.',
  'La caja no trae nada, solamente unas pegatinas. No trae ni una pequeña hoja de instalacion para descargar los drivers. No trae tapas para las salidas que no usemos, una DVI y 3 DisplayPort.'),
 (6,
  2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  'JordiA',
  Decimal('2.5'),
  'Pues podria darle buena nota porque me costo 275 euros y por ese precio cumple, pero el caso es que ya un par de veces en 2 meses me ha hecho una cosa muy rara: se ponen los ventiladores a full, pierdo la señal de las pantallas y la grafica da sensacion de muerta.',
  'Precio competitivo. Por ese precio cumple.',
  'Problemas con los ventiladores. Perdida de señal de las pantallas. Sensacion de fallo grave de la grafica.'),
 (7,
  2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  '__5495',
  Decimal('5.0'),
  'Es una grafica estupenda calidad precio, quizas si tuviera 12 gb vram mejor.',
  'Tecnologia.',
  'VRAM.'),
 (8,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'TLG1983',
  Decimal('0.5'),
  'Antes de comprar esta grafica que sepais que su precio relativamente barato es por algo. Es una loteria, este modelo tiene problemas conocidos con el conector de alimentacion. Si tienes suerte es una ganga, sino te toca gestionar la devolucion, como fue mi caso.',
  'No detectados.',
  'Problemas conocidos con el conector de alimentacion. Posible devolucion del producto.'),
 (9,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'sime_kwode',
  Decimal('3.5'),
  'Es una GPU de gama media muchos la consideran media-baja, pero puedes correr cualquier juego en Ultra. No soporta muy bien el ray tracing en juegos como Fortnite, Elden Ring, Cyberpunk 2077, pero por el precio que tiene hace un trabajo mas que decente.',
  'Funciona decentemente. Relacion calidad/precio. Tiene 2 ventiladores integrados. Los 12GB deberian ser suficientes para casi todo. No se sobrecalienta. Tiene DLSS4.',
  'No presenta mucha mejoria frente a RTX mas antiguas. Conviene mirar benchmarks con juegos que quieras jugar. Puede flaquear en el campo de ray tracing.')]

In [10]:
with conn.cursor() as cursor:
    cursor.execute("""
        DELETE FROM resenas
        WHERE resena_id IN (%s, %s);
    """, (8, 9))

conn.commit()

print("Reseñas duplicadas eliminadas")

Reseñas duplicadas eliminadas

In [11]:
resenas_con_producto = consultas.obtener_resenas_con_producto(conn)

resenas_con_producto

[(1,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'seikozertwo',
  Decimal('5.0'),
  'La NVIDIA GeForce RTX 5070 es una de las mejores opciones para jugadores exigentes y creadores de contenido.',
  'Excelente rendimiento en 1440p. Arquitectura nueva generacion. Buen rendimiento en tareas creativas.',
  'Ninguno hasta la fecha.'),
 (2,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'TLG1983',
  Decimal('0.5'),
  'Antes de comprar esta grafica que sepais que su precio relativamente barato es por algo. Es una loteria, este modelo tiene problemas conocidos con el conector de alimentacion. Si tienes suerte es una ganga, sino te toca gestionar la devolucion, como fue mi caso.',
  'No detectados.',
  'Problemas conocidos con el conector de alimentacion. Posible devolucion del producto.'),
 (4,
  1,
  'MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 Reflex 2 RTX AI DLSS4',
  'MSI',
  'sime_kwode',
  Decimal('3.5'),
  'Es una GPU de gama media muchos la consideran media-baja, pero puedes correr cualquier juego en Ultra. No soporta muy bien el ray tracing en juegos como Fortnite, Elden Ring, Cyberpunk 2077, pero por el precio que tiene hace un trabajo mas que decente.',
  'Funciona decentemente. Relacion calidad/precio. Tiene 2 ventiladores integrados. Los 12GB deberian ser suficientes para casi todo. No se sobrecalienta. Tiene DLSS4.',
  'No presenta mucha mejoria frente a RTX mas antiguas. Conviene mirar benchmarks con juegos que quieras jugar. Puede flaquear en el campo de ray tracing.'),
 (5,
  2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  'YosuMax',
  Decimal('4.0'),
  'Muy buen rendimiento para el precio que tiene. No conocia esta marca, tenia mis dudas antes de comprarla, pero la primera impresion es buena. Acabo de instalarla, aun la he probado poco. Veremos si aguanta el paso del tiempo, de momento creo que hay que darle un voto de confianza a esta marca.',
  'Precio, aunque no es barata, es la mas economica de su rango. Buen rendimiento.',
  'La caja no trae nada, solamente unas pegatinas. No trae ni una pequeña hoja de instalacion para descargar los drivers. No trae tapas para las salidas que no usemos, una DVI y 3 DisplayPort.'),
 (6,
  2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  'JordiA',
  Decimal('2.5'),
  'Pues podria darle buena nota porque me costo 275 euros y por ese precio cumple, pero el caso es que ya un par de veces en 2 meses me ha hecho una cosa muy rara: se ponen los ventiladores a full, pierdo la señal de las pantallas y la grafica da sensacion de muerta.',
  'Precio competitivo. Por ese precio cumple.',
  'Problemas con los ventiladores. Perdida de señal de las pantallas. Sensacion de fallo grave de la grafica.'),
 (7,
  2,
  'Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7 Reflex 2 RTX AI DLSS4',
  'Palit',
  '__5495',
  Decimal('5.0'),
  'Es una grafica estupenda calidad precio, quizas si tuviera 12 gb vram mejor.',
  'Tecnologia.',
  'VRAM.')]

In [12]:
columnas_resenas = [
    "resena_id",
    "producto_id",
    "modelo",
    "marca",
    "usuario",
    "valoracion",
    "texto_resena",
    "pros",
    "contras"
]

df_resenas = pd.DataFrame(resenas_con_producto, columns=columnas_resenas)

df_resenas["valoracion"] = df_resenas["valoracion"].astype(float)

df_resenas

,resena_id,producto_id,modelo,marca,usuario,valoracion,texto_resena,pros,contras
0,1,1,MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 R...,MSI,seikozertwo,5.0,La NVIDIA GeForce RTX 5070 es una de las mejor...,Excelente rendimiento en 1440p. Arquitectura n...,Ninguno hasta la fecha.
1,2,1,MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 R...,MSI,TLG1983,0.5,Antes de comprar esta grafica que sepais que s...,No detectados.,Problemas conocidos con el conector de aliment...
2,4,1,MSI GeForce RTX 5070 VENTUS 2X OC 12GB GDDR7 R...,MSI,sime_kwode,3.5,Es una GPU de gama media muchos la consideran ...,Funciona decentemente. Relacion calidad/precio...,No presenta mucha mejoria frente a RTX mas ant...
3,5,2,Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7...,Palit,YosuMax,4.0,Muy buen rendimiento para el precio que tiene....,"Precio, aunque no es barata, es la mas economi...","La caja no trae nada, solamente unas pegatinas..."
4,6,2,Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7...,Palit,JordiA,2.5,Pues podria darle buena nota porque me costo 2...,Precio competitivo. Por ese precio cumple.,Problemas con los ventiladores. Perdida de señ...
5,7,2,Palit GeForce RTX 5060 Infinity 2 OC 8GB GDDR7...,Palit,__5495,5.0,"Es una grafica estupenda calidad precio, quiza...",Tecnologia.,VRAM.